---
# Audit and Logging Configuration Tasks

- name: Install auditd package
  package:
    name: auditd
    state: present

- name: Backup original auditd configuration
  copy:
    src: /etc/audit/auditd.conf
    dest: /etc/audit/auditd.conf.backup.{{ ansible_date_time.epoch }}
    remote_src: yes
    owner: root
    group: root
    mode: '0640'

- name: Configure auditd daemon
  lineinfile:
    path: /etc/audit/auditd.conf
    regexp: "^{{ item.key }}"
    line: "{{ item.key }} = {{ item.value }}"
    backup: yes
  loop:
    - { key: "max_log_file", value: "{{ baseline_security_auditd_config.max_log_file }}" }
    - { key: "num_logs", value: "{{ baseline_security_auditd_config.num_logs }}" }
    - { key: "max_log_file_action", value: "{{ baseline_security_auditd_config.max_log_file_action }}" }
    - { key: "space_left", value: "{{ baseline_security_auditd_config.space_left }}" }
    - { key: "space_left_action", value: "{{ baseline_security_auditd_config.space_left_action }}" }
    - { key: "admin_space_left", value: "{{ baseline_security_auditd_config.admin_space_left }}" }
    - { key: "admin_space_left_action", value: "{{ baseline_security_auditd_config.admin_space_left_action }}" }
    - { key: "disk_full_action", value: "{{ baseline_security_auditd_config.disk_full_action }}" }
    - { key: "disk_error_action", value: "{{ baseline_security_auditd_config.disk_error_action }}" }
    - { key: "flush", value: "{{ baseline_security_auditd_config.flush }}" }
    - { key: "freq", value: "{{ baseline_security_auditd_config.freq }}" }
    - { key: "log_format", value: "{{ baseline_security_auditd_config.log_format }}" }
  notify: restart auditd

- name: Create audit rules directory
  file:
    path: /etc/audit/rules.d
    state: directory
    owner: root
    group: root
    mode: '0750'

- name: Clear existing audit rules
  file:
    path: /etc/audit/rules.d/audit.rules
    state: absent

- name: Configure comprehensive audit rules
  blockinfile:
    path: /etc/audit/rules.d/audit.rules
    create: yes
    owner: root
    group: root
    mode: '0640'
    marker: "# {mark} ANSIBLE MANAGED BLOCK - {{ item.name }}"
    block: "{{ item.rules | join('\n') }}"
  loop:
    - name: "Buffer Configuration"
      rules:
        - "# Buffer size configuration"
        - "-b 8192"
        - "# Failure mode (0=silent, 1=printk, 2=panic)"
        - "-f 1"
        - "# Rate limit for audit messages"
        - "-r 1000"

    - name: "Time Change Monitoring"
      rules:
        - "# Monitor time changes"
        - "-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change"
        - "-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change"
        - "-a always,exit -F arch=b64 -S clock_settime -k time-change"
        - "-a always,exit -F arch=b32 -S clock_settime -k time-change"
        - "-w /etc/localtime -p wa -k time-change"

    - name: "User and Group Information"
      rules:
        - "# Monitor user and group changes"
        - "-w /etc/group -p wa -k identity"
        - "-w /etc/passwd -p wa -k identity"
        - "-w /etc/gshadow -p wa -k identity"
        - "-w /etc/shadow -p wa -k identity"
        - "-w /etc/security/opasswd -p wa -k identity"

    - name: "Network Configuration"
      rules:
        - "# Monitor network configuration changes"
        - "-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale"
        - "-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale"
        - "-w /etc/issue -p wa -k system-locale"
        - "-w /etc/issue.net -p wa -k system-locale"
        - "-w /etc/hosts -p wa -k system-locale"
        - "-w /etc/network -p wa -k system-locale"
        - "-w /etc/networks -p wa -k system-locale"
        - "-w /etc/sysconfig/network -p wa -k system-locale"

    - name: "Login/Logout Events"
      rules:
        - "# Monitor login/logout events"
        - "-w /var/log/faillog -p wa -k logins"
        - "-w /var/log/lastlog -p wa -k logins"
        - "-w /var/log/tallylog -p wa -k logins"
        - "-w /var/run/utmp -p wa -k session"
        - "-w /var/log/wtmp -p wa -k logins"
        - "-w /var/log/btmp -p wa -k logins"

    - name: "Process and Session Initiation"
      rules:
        - "# Monitor process and session initiation"
        - "-w /var/run/utmp -p wa -k session"
        - "-w /var/log/wtmp -p wa -k session"
        - "-w /var/log/btmp -p wa -k session"

    - name: "Discretionary Access Control"
      rules:
        - "# Monitor discretionary access control permission modifications"
        - "-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod"
        - "-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 -F auid!=4294967295 -k perm_mod"
        - "-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod"
        - "-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 -F auid!=4294967295 -k perm_mod"
        - "-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"
        - "-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod"

    - name: "Unsuccessful File Access"
      rules:
        - "# Monitor unsuccessful unauthorized file access attempts"
        - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access"
        - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access"
        - "-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access"
        - "-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access"

    - name: "Privileged Commands"
      rules:
        - "# Monitor use of privileged commands"
        - "-a always,exit -F path=/usr/bin/wall -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/write -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/chfn -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/chsh -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/newgrp -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/chage -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/gpasswd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/passwd -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/su -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/sudo -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/mount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
        - "-a always,exit -F path=/usr/bin/umount -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"

    - name: "Media Export"
      rules:
        - "# Monitor successful file system mounts"
        - "-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"
        - "-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts"

    - name: "File Deletion Events"
      rules:
        - "# Monitor file deletion events by users"
        - "-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete"
        - "-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 -F auid!=4294967295 -k delete"

    - name: "Sudoers Changes"
      rules:
        - "# Monitor changes to sudoers"
        - "-w /etc/sudoers -p wa -k scope"
        - "-w /etc/sudoers.d/ -p wa -k scope"

    - name: "System Administrator Actions"
      rules:
        - "# Monitor system administrator actions"
        - "-w /var/log/sudo.log -p wa -k actions"

    - name: "Kernel Module Loading"
      rules:
        - "# Monitor kernel module loading and unloading"
        - "-w /sbin/insmod -p x -k modules"
        - "-w /sbin/rmmod -p x -k modules"
        - "-w /sbin/modprobe -p x -k modules"
        - "-a always,exit -F arch=b64 -S init_module -S delete_module -k modules"

    - name: "System Configuration Files"
      rules:
        - "# Monitor critical system configuration files"
        - "-w /etc/ssh/sshd_config -p wa -k ssh_config"
        - "-w /etc/pam.d/ -p wa -k pam"
        - "-w /etc/security/ -p wa -k security_config"
        - "-w /etc/audit/ -p wa -k audit_config"
        - "-w /etc/systemd/ -p wa -k systemd_config"
        - "-w /etc/crontab -p wa -k cron"
        - "-w /etc/cron.allow -p wa -k cron"
        - "-w /etc/cron.deny -p wa -k cron"
        - "-w /etc/cron.d/ -p wa -k cron"
        - "-w /etc/cron.daily/ -p wa -k cron"
        - "-w /etc/cron.hourly/ -p wa -k cron"
        - "-w /etc/cron.monthly/ -p wa -k cron"
        - "-w /etc/cron.weekly/ -p wa -k cron"

    - name: "Finalize Rules"
      rules:
        - "# Make the configuration immutable"
        - "-e 2"
  notify: restart auditd

- name: Generate audit rules from template
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/99-custom.rules
    owner: root
    group: root
    mode: '0640'
  notify: restart auditd

- name: Configure rsyslog for audit logs
  blockinfile:
    path: /etc/rsyslog.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK - Audit Logging"
    block: |
      # Audit log forwarding
      $ModLoad imfile
      $InputFileName /var/log/audit/audit.log
      $InputFileTag auditd:
      $InputFileStateFile audit_log
      $InputFileSeverity info
      $InputFileFacility local6
      $InputRunFileMonitor

      # Forward audit logs to central server if configured
      {% if baseline_security_audit_logging.setup_remote_logging and baseline_security_audit_logging.remote_log_server != "" %}
      local6.* @@{{ baseline_security_audit_logging.remote_log_server }}:{{ baseline_security_audit_logging.remote_log_port }}
      {% endif %}
  notify: restart rsyslog
  when: baseline_security_audit_logging.configure_rsyslog | default(true)

- name: Configure journald for audit integration
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }}={{ item.value }}"
  loop:
    - { key: "Storage", value: "persistent" }
    - { key: "Compress", value: "yes" }
    - { key: "Seal", value: "yes" }
    - { key: "ForwardToSyslog", value: "yes" }
    - { key: "MaxRetentionSec", value: "1month" }
    - { key: "MaxFileSec", value: "1week" }
    - { key: "SystemMaxUse", value: "1G" }
    - { key: "SystemMaxFileSize", value: "100M" }
  notify: restart systemd-journald
  when: baseline_security_audit_logging.configure_journald | default(true)

- name: Configure logrotate for audit logs
  template:
    src: audit-logrotate.j2
    dest: /etc/logrotate.d/audit
    owner: root
    group: root
    mode: '0644'
  when: baseline_security_audit_logging.setup_log_rotation | default(true)

- name: Enable process accounting
  block:
    - name: Install process accounting
      package:
        name: psacct
        state: present

    - name: Enable process accounting service
      systemd:
        name: psacct
        enabled: yes
        state: started

    - name: Configure process accounting log rotation
      template:
        src: psacct-logrotate.j2
        dest: /etc/logrotate.d/psacct
        owner: root
        group: root
        mode: '0644'

  when: baseline_security_audit_logging.enable_process_accounting | default(true)

- name: Create audit log analysis script
  template:
    src: analyze-audit-logs.sh.j2
    dest: /usr/local/bin/analyze-audit-logs.sh
    owner: root
    group: root
    mode: '0755'

- name: Schedule audit log analysis
  cron:
    name: "Analyze audit logs"
    minute: "0"
    hour: "6"
    job: "/usr/local/bin/analyze-audit-logs.sh >> /var/log/security-baseline/audit-analysis.log 2>&1"
    user: root

- name: Create audit monitoring script
  template:
    src: monitor-audit.sh.j2
    dest: /usr/local/bin/monitor-audit.sh
    owner: root
    group: root
    mode: '0755'

- name: Schedule audit monitoring
  cron:
    name: "Monitor audit system"
    minute: "*/15"
    job: "/usr/local/bin/monitor-audit.sh >> /var/log/security-baseline/audit-monitoring.log 2>&1"
    user: root

- name: Configure audit log permissions
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop:
    - { path: "/var/log/audit", owner: "root", group: "root", mode: "0750" }
    - { path: "/var/log/audit/audit.log", owner: "root", group: "root", mode: "0640" }
    - { path: "/etc/audit", owner: "root", group: "root", mode: "0750" }
    - { path: "/etc/audit/auditd.conf", owner: "root", group: "root", mode: "0640" }
  ignore_errors: yes

- name: Enable and start auditd service
  systemd:
    name: auditd
    enabled: yes
    state: started

- name: Verify audit system is working
  command: auditctl -l
  register: audit_rules_check
  changed_when: false

- name: Log audit configuration completion
  lineinfile:
    path: /var/log/security-baseline/audit-config.log
    create: yes
    owner: root
    group: root
    mode: '0640'
    line: "{{ ansible_date_time.iso8601 }} - Audit system configured with {{ audit_rules_check.stdout_lines | length }} rules"

- name: Create audit report template
  template:
    src: audit-report.sh.j2
    dest: /usr/local/bin/audit-report.sh
    owner: root
    group: root
    mode: '0755'

- name: Display audit configuration summary
  debug:
    msg:
      - "Audit system configuration completed"
      - "Audit rules configured: {{ audit_rules_check.stdout_lines | length }}"
      - "Log file size: {{ baseline_security_auditd_config.max_log_file }}MB"
      - "Number of log files: {{ baseline_security_auditd_config.num_logs }}"
      - "Space left action: {{ baseline_security_auditd_config.space_left_action }}"
      - "Remote logging: {{ 'Enabled' if baseline_security_audit_logging.setup_remote_logging else 'Disabled' }}"